<Widget>:
    font_name: 'OpenSans-Bold.ttf'
    font_size: dp(25)

<SelectableLabel>:
    canvas.before:
        Color:
            rgba: (.0, 0.9, .1, .3) if self.selected else (0, 0, 0, 1)
        Rectangle:
            size: self.size
            pos: self.pos
    name: u''
    directory: u''
    BoxLayout:
        orientation: 'vertical'
        Label:
            text: root.name
        Label:
            text: root.directory if root.directory != '.' else ''
            font_size: dp(15)

<Main>:
    canvas.before:
        Color:
            rgba: 0.2, 0.2, 0.2, 1
        Rectangle:
            pos: self.pos
            size: self.size
    manager: _screen_manager
    ScreenManager:
        id: _screen_manager
        Screen:
            name: 'main'
            BoxLayout:
                orientation: 'vertical'
                Button:
                    size_hint: 1, .1
                    text: 'Shutdown'
                    on_release: app.shutdown()
                BoxLayout:
                    size_hint: 1, .9
                    Image:
                        source: 'gfx/no-figurine.png'
                        size: 250, 250
                    BigLabel:
                        text: 'Place a figurine on top of the box'
                        text_size: self.width, None
                        size: self.texture_size
                        font_size: dp(40)

        Screen:
            name: 'playing'
            BoxLayout:
                orientation: 'vertical'
                BoxLayout:
                    size_hint: 1, .1
                    spacing: dp(10)
                    Slider:
                        id: volume_slider
                        size_hint: .6, 1
                        range: (0, 400)
                        value: 100
                        step: 5
                        cursor_size: (dp(50), dp(50))
                    Button:
                        size_hint: .2, 1
                        text: 'Delete'
                        on_release: app.delete_figurine()
                    Button:
                        size_hint: .2, 1
                        text: 'Shutdown'
                        on_release: app.shutdown()
                Label:
                    id: audio_name
                    size_hint: 1, .1
                    text: ''
                BoxLayout:
                    size_hint: 1, .7
                    Image:
                        source: 'gfx/figurine.png'
                        size: 250, 250
                    BigLabel:
                        id: playing_label
                        text: 'Playing..'
                        text_size: self.width, None
                        size: self.texture_size
                BoxLayout:
                    size_hint: 1, .1
                    spacing: dp(10)
                    ReleasableSlider:
                        id: seek_slider
                        size_hint: .7, 1
                        range: (0, 1)
                        value: 0
                        step: 0.05
                        on_release: app.seek_to_user()
                        value_track: True
                        value_track_color: [0.15, 0.7, 0.9, 1]
                        cursor_size: (dp(50), dp(50))
                    Button:
                        id: play_pause_button
                        size_hint: .2, 1
                        text: ''
                        on_release: app.toggle_pause()
                    Label:
                        id: seek_time
                        size_hint: .1, 1
                        text: ''

        Screen:
            name: 'create_figurine'
            BoxLayout:
                orientation: 'vertical'
                Label:
                    size_hint: 1, .1
                    text: 'New figurine, please select an audio file.'
                BoxLayout:
                    size_hint: 1, .1
                    ToggleButton:
                        text: 'Show all'
                        group: 'audio_list_filter'
                        font_size: dp(20)
                        state: 'down'
                        on_release: audio_list.show_all()
                        allow_no_selection: False
                    ToggleButton:
                        text: 'Show unused'
                        group: 'audio_list_filter'
                        font_size: dp(20)
                        on_release: audio_list.show_unused()
                        allow_no_selection: False
                AudioList:
                    id: audio_list
                    # Don't specify a size_hint, otherwise scrolling gets messed up
                    scroll_type: ['bars', 'content']
                    scroll_wheel_distance: dp(114)
                    bar_width: dp(40)
                    viewclass: 'SelectableLabel'
                    SelectableRecycleBoxLayout:
                        default_size: None, dp(56)
                        default_size_hint: 1, None
                        size_hint_y: None
                        height: self.minimum_height
                        orientation: 'vertical'
                        spacing: dp(2)
                BoxLayout:
                    size_hint: 1, .2
                    Button:
                        text: 'Cancel'
                        on_release: _screen_manager.current = 'main'
                    Button:
                        text: 'Save'
                        on_release: app.save_figurine()
