<Main>:
    manager: _screen_manager
    AnchorLayout:
        anchor_x: 'center'
        anchor_y: 'top'
        ScreenManager:
            size_hint: 1, .9
            id: _screen_manager
            Screen:
                name: 'main'
                BoxLayout:
                    Image:
                        source: 'gfx/no-figurine.png'
                        size: 250, 250
                    Label: 
                        text: 'Place a figurine on top of the box'

            Screen:
                name: 'playing'
                BoxLayout:
                    orientation: 'vertical'
                    Slider:
                        id: volume_slider
                        range: (0, 1)
                        value: 0.25
                        step: 0.05
                    BoxLayout:
                        Image:
                            source: 'gfx/figurine.png'
                            size: 250, 250
                        Label:
                            text: 'Playing..'
                    ReleasableSlider:
                        id: seek_slider
                        range: (0, 1)
                        value: 0
                        step: 0.05
                        on_release: app.seek_to_user()
                    Button:
                        text: 'Play / Pause'
                        on_release: app.togglePause()

            Screen:
                name: 'settings'
                AnchorLayout:
                    anchor_x: 'center'
                    anchor_y: 'top'
                    size_hint: .1, 1
                    Button:
                        text: 'Back'
                        on_release:
                            _screen_manager.current = _screen_manager.state
                AnchorLayout:
                    anchor_x: 'center'
                    anchor_y: 'bottom'
                    Label:
                        text: 'Some settings'
            Screen:
                name: 'wifi'
                AnchorLayout:
                    anchor_x: 'center'
                    anchor_y: 'top'
                    size_hint: .1, 1
                    Button:
                        text: 'Back'
                        on_release: _screen_manager.current = _screen_manager.state
                AnchorLayout:
                    anchor_x: 'center'
                    anchor_y: 'bottom'
                    ListView:
                        id: wifi_networks
    AnchorLayout:
        anchor_x: 'center'
        anchor_y: 'bottom'
        BoxLayout:
            orientation: 'horizontal'
            size_hint: 1, .1
            Button:
                on_release: _screen_manager.current = 'settings'
                Image:
                    center: self.parent.center
                    source: 'gfx/settings.png'
            Button:
                on_release: _screen_manager.current = 'wifi'
                Image:
                    center: self.parent.center
                    source: 'gfx/no-connection.png'
