<Main>:
    manager: _screen_manager
    ScreenManager:
        id: _screen_manager
        Screen:
            name: 'main'
            BoxLayout:
                Image:
                    source: 'gfx/no-figurine.png'
                    size: 250, 250
                Label: 
                    text: 'Place a figurine on top of the box'

        Screen:
            name: 'playing'
            BoxLayout:
                orientation: 'vertical'
                BoxLayout:
                    size_hint: 1, .1
                    Slider:
                        id: volume_slider
                        range: (0, 100)
                        value: 25
                        step: 5
                    Button:
                        text: 'Play / Pause'
                        on_release: app.togglePause()
                BoxLayout:
                    size_hint: 1, .8
                    Image:
                        source: 'gfx/figurine.png'
                        size: 250, 250
                    Label:
                        text: 'Playing..'
                ReleasableSlider:
                    size_hint: 1, .1
                    id: seek_slider
                    range: (0, 1)
                    value: 0
                    step: 0.05
                    on_release: app.seek_to_user()

        Screen:
            name: 'create_figurine'
            BoxLayout:
                orientation: 'vertical'
                ListView:
                    id: audio_list
                BoxLayout:
                    Button:
                        text: 'Cancel'
                        on_release: _screen_manager.current = _screen_manager.state
                    Button:
                        text: 'Save'
                        on_release: app.save_figurine()
